name: Lint
on: [push, pull_request]
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Print tree
        run: find . -not -path './.git/*'
